# Generated by Django 2.0.1 on 2018-01-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20180128_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
