# Generated by Django 2.0.1 on 2018-01-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0020_auto_20180128_1504'),
    ]

    operations = [
    ]
